---
rules:
  indent:
    - 1
    - 2
    - SwitchCase: 1
      VariableDeclarator:
        var: 2
  quotes:
    - 1
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 1
    - always
  no-shadow:
    - 2
    - builtinGlobals: true
  no-shadow-restricted-names: 2
  no-unexpected-multiline: 2
  space-before-function-paren:
    - 1
    - anonymous: always
      named: never
env:
  commonjs: true
extends: eslint:recommended
